id: P006622
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20914
  title: མགོ་ལོག་གི་ལོ་ངོ་བཞི་བཅུ། ༡༩༥༤་ལོ་ནས ༡༩༩༤་ལོའི་བར།
  author: ''
  volumes:
    9d2addd03f33498d928808bd69c02403:
      image_group_id: I5714
      title: ''
      volume_number: 1
      total_pages: 668
      base_file: v001.txt
